# Use the official Node.js 16 image as a parent image
FROM oven/bun:alpine as base

# Set workdir
WORKDIR /app

FROM base as install
# Copy the necessary monorepo files to the container
COPY . .

# Install workspace dependencies
RUN bun install

FROM install as build

RUN cd apps/@tinie-client && bun run build
COPY apps/@tinie-client/dist apps/@tinie-server/public

