# @format

# docker-compose.full.yml

version: '3.8'
services:
    dynamodb:
        image: amazon/dynamodb-local
        container_name: tinie-dynamodb
        ports:
            - '8000:8000'
        command: '-jar DynamoDBLocal.jar -sharedDb'
    redis:
        image: redis:latest
        container_name: tinie-redis
        ports:
            - '6379:6379'
    tinie:
        image: tinie-webserver:latest
        container_name: tinie-webserver
        restart: unless-stopped
        ports:
            - '3000:3000'
        command: >
            sh -c "bun run start:server"
        environment:
            - AWS_REGION=${AWS_REGION}
            - AWS_DYNAMO_ENDPOINT=http://dynamodb:8000
            - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
            - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
            - REDIS_CONNECT=redis://redis:6379/0
            - REDIS_TTL=${REDIS_TTL}
            - WORKER_CONNECT=host.docker.internal:8787
            - WORKER_SECRET=${WORKER_SECRET}
            - PORT=3000
            - HOST=localhost
        depends_on:
            - dynamodb
            - redis
