# Use the official Node.js 16 image as a parent image
FROM oven/bun:alpine as base

# Set workdir
WORKDIR /app


FROM base as install
# Copy the necessary monorepo files to the container
COPY package.json package.json
COPY turbo.json turbo.json
COPY ./apps/@tinie-server ./apps/@tinie-server
COPY ./packages ./packages

# Install workspace dependencies
RUN bun install
