# This action is used to deploy the Cloudflare worker used as Zookeeper

name: Deploy Webserver to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Build & Deploy Server to Render.com
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render
        env:
            deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
            curl "$deploy_url"